### ISSUE TITLE
approach question / tmp file failures

### ISSUE THREAD

**Issue by nevion** [cloudhan/rules_cuda#3]
Do you use the crosstool wrapper approach or just custom rules to compile cuda files?

What's interesting is by adding -objtemp to all commands a wrapper script that multiplexes nvcc and host compiler, the random temp file failures seem to go away completely - it was important to do it for all intermediate library linkings.  I also override TMP/TMPDIR TMP_DIR=cwd for nvcc command.  Could also be apparently eliminated, still subject to random failure.

**Comment by cloudhan** [comment]
It is custom rules. There is some limitation of cc_* rules that it cannot fit into nvcc seperate compilation mode. The complex thing happens in [toolchain_config_lib.bzl](https://github.com/cloudhan/rules_cuda/blob/main/cuda/private/toolchain_config_lib.bzl). It is (hopefully) a full reimplementation for [cc_toolchain_config_lib.bzl](https://github.com/bazelbuild/bazel/blob/c8116b166cc09e1607db437ed4395a3153b45629/tools/cpp/cc_toolchain_config_lib.bzl) so that I can do [cc_* rules like toolchain configuration](https://github.com/bazelbuild/bazel/blob/master/tools/cpp/windows_cc_toolchain_config.bzl). In bazel, this DSL interpreter is implemented in java...

`-objtemp` won't fix/eliminate the `/tmp/tmpxft` failure actually, but it indeed alleviate the problem. Imagining `kernel.cu` is compiled with different defines, in targets `kernel_with_def1` and `kernel_with_def2` in the same package. Then there is still possibility (albeit low) naming conflict happens when `linux-sandbox` is used. And this had been actually happening in the [nccl examples](https://github.com/cloudhan/rules_cuda_examples/blob/c5380a9c229e6b6d15560c97e2fe5f5cd671af59/nccl/nccl.bzl#L49-L66) **if the file was not copied**.

`TMP_DIR`, however, is not respected, if you do not use `-keep`.

**Comment by cloudhan** [comment]
See [README.md#known-issue](https://github.com/cloudhan/rules_cuda/blob/11a1f1552c8e7883373431cde796cf262bdd70b6/README.md#known-issue). And I think tensorflow is using `--spawn_strategy standalone` for this reason.

**Comment by nevion** [comment]
yes so I observed the same issue with nccl, I've never used this project before and still haven't, but I did have to deal with this issue.  I haven't had to alter the spawn strategy; I used to see it just about any fresh build with nccl especially.  But I haven't seen it once since I had TMPDIR=cwd everywhere + objtemp, including when linking.  I do understand that if the filenames are still relying on randomness they will conflict potentially; I also remember nvidia made these filenames deterministic I think in 11.6+.  Ultimately it doesn't have my trust but practically speaking I haven't seen it for months.

Also if nccl is the most frequent offender, simply make less files in the rules you have there; with the right tricks you can have say only 8 cu files with all the functions populated because there's just trivial macro expansion happening
